# Generated by Django 2.0 on 2021-03-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baming', models.TextField()),
                ('guanzhuliang', models.TextField()),
                ('fatieshu', models.TextField()),
            ],
            options={
                'db_table': 'tieba_infor',
            },
        ),
    ]
